### ISSUE TITLE
clinvar annotator needs more filter options for conflicting pathogenecity

### ISSUE THREAD

**Issue by antonkulaga** [KarchinLab/open-cravat-modules-karchinlab#12]
## Feature request: ## 

More details in the filter options for the ClinVar annotator  (Conflicting in interpretations of pathogenicity category in Clinical significance)

You can also just let us know which ClinVar parser you used in the module, so we can implement the feature ourselves and send you the pull request.

## Description of a problem: ## 
```
ClinVar → Clinical Significance → One Of (select): 
Conflicting interpretations of pathogenicity
Conflicting interpretations of pathogenicity may include any of the variants :
-  Benign+ Likely benign
- Pathogenic  + likely pathogenic
- Benign + Uncertain significance 
- etc.
```
And we don’t know which until we go to the external link in the ClinVar widget.

## Example ##

For example, our aim is to filter (include) Pathogenic + Risk factor + Likely pathogenic variants using ClinVar filter. 
We need to exclude: Benign, Likely benign.  
If we choose -    “Conflicting interpretations of pathogenicity significance” we will get results that meet our request and results that do not. For getting the additional info we have to go to the link in the ClinVar widget info
```
ClinVar widget info:
Significance:    Conflicting interpretations of pathogenicity
Review Status:    criteria provided, conflicting interpretations
ClinVar ID: [212360](https://www.ncbi.nlm.nih.gov/clinvar/variation/212360/?new_evidence=true)
```
After going to this link we can see (e.g):
```
Interpretation:
Conflicting interpretations of pathogenicity​
Uncertain significance(1); Benign(2); Likely benign(1)  
```
here we can see a list of the options that led to the categorization of “Conflicting interpretations of pathogenicity significance” and the number of studies.

## Our feature request: ##
Is it possible to pull these variants into the filter window, e.g
```
ClinVar → Clinical Significance → One Of (select): 
Conflicting interpretations of pathogenicity (Uncertain significance(1); Benign(2); Likely benign(1)) 
```
So we can filter just variants that meet our request.

**Comment by mryaninsilico** [comment]
Anton,

 

Thanks for the detailed feature request and for the offer to help with implementation of the feature.

 

We will review the details of the current Clinvar data build process to see if the additional information you are requesting is available and could be incorporated into our annotator.

 

Should just take a few days. 

 

Thanks,

 

Michael Ryan, PhD

In Silico Solutions

 

From: Anton Kulaga ***@***.***> 
Sent: Monday, June 6, 2022 2:16 PM
To: KarchinLab/open-cravat-modules-karchinlab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KarchinLab/open-cravat-modules-karchinlab] clinvar annotator needs more filter options for conflicting pathogenecity (Issue #12)

 


Feature request:


More details in the filter options for the ClinVar annotator (Conflicting in interpretations of pathogenicity category in Clinical significance)

You can also just let us know which ClinVar parser you used in the module, so we can implement the feature ourselves and send you the pull request.


Description of a problem:

ClinVar → Clinical Significance → One Of (select): 
 
Conflicting interpretations of pathogenicity
 
Conflicting interpretations of pathogenicity may include any of the variants :
 
-  Benign+ Likely benign
 
- Pathogenic  + likely pathogenic
 
- Benign + Uncertain significance 
 
- etc.
 

And we don’t know which until we go to the external link in the ClinVar widget.


Example


For example, our aim is to filter (include) Pathogenic + Risk factor + Likely pathogenic variants using ClinVar filter.
We need to exclude: Benign, Likely benign.
If we choose - “Conflicting interpretations of pathogenicity significance” we will get results that meet our request and results that do not. For getting the additional info we have to go to the link in the ClinVar widget info

ClinVar widget info:
 
Significance:    Conflicting interpretations of pathogenicity
 
Review Status:    criteria provided, conflicting interpretations
 
ClinVar ID: [212360](https://www.ncbi.nlm.nih.gov/clinvar/variation/212360/?new_evidence=true)
 

After going to this link we can see (e.g):

Interpretation:
 
Conflicting interpretations of pathogenicity​
 
Uncertain significance(1); Benign(2); Likely benign(1)  
 

here we can see a list of the options that led to the categorization of “Conflicting interpretations of pathogenicity significance” and the number of studies.


Our feature request:


Is it possible to pull these variants into the filter window, e.g

ClinVar → Clinical Significance → One Of (select): 
 
Conflicting interpretations of pathogenicity (Uncertain significance(1); Benign(2); Likely benign(1)) 
 

So we can filter just variants that meet our request.

**Comment by antonkulaga** [comment]
@mryaninsilico is it published anywhere? Me and @OlgaBorysova checked and both OakVar and OpenCravat stores seem to have older clinvar module

**Comment by mryaninsilico** [comment]
It is published in the official OpenCRAVAT store.  The version is 2022.06.14.  Is that the version you are seeing?  When I run oc module ls -a  I get:

**Comment by mryaninsilico** [comment]
Anton,

 

A new version of the clinvar module has been published.  Version 2022.06.14

 

The new version has updated clinvar data and includes a new column – Significance Detail.  When Significance is ‘Conflicting interpretations of pathogenicity’ the Significance Detail has the conflicting significance information – for example: Pathogenic(21)| Likely pathogenic(10)| Uncertain significance(1)| Benign(1)

 

This makes it possible now to filter on significance of pathogenic OR Significance Detail contains ‘pathogenic’.  

 

Please install the new clinvar module when you have a chance and close out the feature request if it meets your needs.

 

Thanks again for the feedback.

 

Michael Ryan, PhD

In Silico Solutions

 

From: Anton Kulaga ***@***.***> 
Sent: Monday, June 6, 2022 2:16 PM
To: KarchinLab/open-cravat-modules-karchinlab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KarchinLab/open-cravat-modules-karchinlab] clinvar annotator needs more filter options for conflicting pathogenecity (Issue #12)

 


Feature request:


More details in the filter options for the ClinVar annotator (Conflicting in interpretations of pathogenicity category in Clinical significance)

You can also just let us know which ClinVar parser you used in the module, so we can implement the feature ourselves and send you the pull request.


Description of a problem:

ClinVar → Clinical Significance → One Of (select): 
 
Conflicting interpretations of pathogenicity
 
Conflicting interpretations of pathogenicity may include any of the variants :
 
-  Benign+ Likely benign
 
- Pathogenic  + likely pathogenic
 
- Benign + Uncertain significance 
 
- etc.
 

And we don’t know which until we go to the external link in the ClinVar widget.


Example


For example, our aim is to filter (include) Pathogenic + Risk factor + Likely pathogenic variants using ClinVar filter.
We need to exclude: Benign, Likely benign.
If we choose - “Conflicting interpretations of pathogenicity significance” we will get results that meet our request and results that do not. For getting the additional info we have to go to the link in the ClinVar widget info

ClinVar widget info:
 
Significance:    Conflicting interpretations of pathogenicity
 
Review Status:    criteria provided, conflicting interpretations
 
ClinVar ID: [212360](https://www.ncbi.nlm.nih.gov/clinvar/variation/212360/?new_evidence=true)
 

After going to this link we can see (e.g):

Interpretation:
 
Conflicting interpretations of pathogenicity​
 
Uncertain significance(1); Benign(2); Likely benign(1)  
 

here we can see a list of the options that led to the categorization of “Conflicting interpretations of pathogenicity significance” and the number of studies.


Our feature request:


Is it possible to pull these variants into the filter window, e.g

ClinVar → Clinical Significance → One Of (select): 
 
Conflicting interpretations of pathogenicity (Uncertain significance(1); Benign(2); Likely benign(1)) 
 

So we can filter just variants that meet our request.
